baseURL = 'https://k3s-at-home.com'
languageCode = 'en-us'
title = 'K3s-at-Home'
theme = 'hugo-theme-relearn'

[params]
  collapsibleMenu = true
  alwaysopen = false
  customCSS = ["css/custom.css"]
  google_adsense = 'ca-pub-9380661630053300'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.imports]]
    path = 'github.com/hugomods/google-adsense'
